name: QuickInventory
version: "1.11"
main: com.nokhoon.quickinventory.PluginMain
description: Open crafting table and ender chest
api-version: "1.21"
author: "0x0804ac"
commands: 
  ct:
    description: Player opens a crafting table inventory
    usage: /ct
  ec:
    description: Player opens their ender chest inventory
    usage: /ec