name: QuickInventory
version: "1.10"
main: com.nokhoon.quickinventory.PluginMain
description: Open crafting table and ender chest
api-version: 1.20
author: "0x0804ac"
commands: 
  ct:
    description: opens crafting table inventory
    usage: /ct
  ec:
    description: opens ender chest inventory
    usage: /ec