name: QuickInventory
version: "1.8"
main: com.nokhoon.quickinventory.PluginMain
description: quick access to crafting table and ender chest
api-version: 1.18
author: "0x0804ac"
commands: 
  ct:
    description: opens crafting table inventory
    usage: /ct
  ec:
    description: opens ender chest inventory
    usage: /ec