name: QuickInventory
version: "1.5"
main: com.nokhoon.quickinventory.PluginMain
description: quick access to crafting table and ender chest
api-version: 1.17
author: "0x0804ac"

commands: 
  ct:
    description: Player opens crafting table inventory
    usage: /ct
  ec:
    description: Player opens own ender chest inventory
    usage: /ec